-- Drop security domain
DROP TABLE IF EXISTS module_view CASCADE;
DROP TABLE IF EXISTS role_permission CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS app_view CASCADE;
DROP TABLE IF EXISTS module CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS app_role CASCADE;
DROP TABLE IF EXISTS person CASCADE;