
-- Billing domain
CREATE TABLE proforma_invoice (
  id BIGSERIAL PRIMARY KEY,
  stay_id BIGINT NOT NULL,
  room_reservation_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  updated_at TIMESTAMP,
  deleted_by BIGINT,
  deleted_at TIMESTAMP,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT uk_proforma_invoice_stay UNIQUE (stay_id),
  CONSTRAINT fk_proforma_invoice_stay FOREIGN KEY (stay_id) REFERENCES stay (id),
  CONSTRAINT fk_proforma_invoice_reservation FOREIGN KEY (room_reservation_id) REFERENCES room_reservation (id),
  CONSTRAINT fk_proforma_invoice_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT ck_proforma_invoice_values CHECK (subtotal >= 0 AND tax_amount >= 0 AND discount_amount >= 0 AND total_amount >= 0)
);

CREATE TABLE invoice (
  id BIGSERIAL PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  stay_id BIGINT NOT NULL,
  invoice_number VARCHAR(60) NOT NULL,
  issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  invoice_status VARCHAR(40) NOT NULL DEFAULT 'ISSUED',
  created_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  updated_at TIMESTAMP,
  deleted_by BIGINT,
  deleted_at TIMESTAMP,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT uk_invoice_number UNIQUE (invoice_number),
  CONSTRAINT uk_invoice_stay UNIQUE (stay_id),
  CONSTRAINT fk_invoice_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT fk_invoice_stay FOREIGN KEY (stay_id) REFERENCES stay (id),
  CONSTRAINT ck_invoice_values CHECK (subtotal >= 0 AND tax_amount >= 0 AND discount_amount >= 0 AND total_amount >= 0)
);

CREATE TABLE partial_payment (
  id BIGSERIAL PRIMARY KEY,
  room_reservation_id BIGINT,
  invoice_id BIGINT,
  payment_method_id BIGINT NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payment_reference VARCHAR(120),
  created_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  updated_at TIMESTAMP,
  deleted_by BIGINT,
  deleted_at TIMESTAMP,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT fk_partial_payment_reservation FOREIGN KEY (room_reservation_id) REFERENCES room_reservation (id),
  CONSTRAINT fk_partial_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id),
  CONSTRAINT fk_partial_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_method (id),
  CONSTRAINT ck_partial_payment_amount CHECK (amount > 0),
  CONSTRAINT ck_partial_payment_source CHECK (room_reservation_id IS NOT NULL OR invoice_id IS NOT NULL)
);

CREATE TABLE invoice_detail (
  id BIGSERIAL PRIMARY KEY,
  invoice_id BIGINT NOT NULL,
  product_id BIGINT,
  service_id BIGINT,
  description VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  total_amount NUMERIC(12,2) NOT NULL,
  created_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  updated_at TIMESTAMP,
  deleted_by BIGINT,
  deleted_at TIMESTAMP,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT fk_invoice_detail_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id),
  CONSTRAINT fk_invoice_detail_product FOREIGN KEY (product_id) REFERENCES product (id),
  CONSTRAINT fk_invoice_detail_service FOREIGN KEY (service_id) REFERENCES service (id),
  CONSTRAINT ck_invoice_detail_values CHECK (quantity > 0 AND unit_price >= 0 AND total_amount >= 0),
  CONSTRAINT ck_invoice_detail_item CHECK (product_id IS NOT NULL OR service_id IS NOT NULL)
);
